# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:                                       # type d'encodage
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:                              #hierarchy des rôles
        ROLE_ADMIN:       ROLE_USER              #ROLE_USER : authentifié
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CLIENT:      ROLE_USER
        ROLE_VENDEUR:     ROLE_ADMIN

    providers:                          #provider pour génerer les clés
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

#            form_login:
#                csrf_provider: form.csrf_provider
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
            logout:       true
            anonymous:    true

    access_control:    #les routes à controller
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/backOffice/Produit/show, role: ROLE_USER }
        - { path: ^/backOffice, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
