<?php

namespace projet2sdvBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * sproduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sproduitsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getProduits($page, $nbParPage){
		$qb=$this->createQueryBuilder('p');
        $qb->addselect('p.id', 't.libelle', 'p.nom', 'p.prix', 'p.photo')
            ->join( 'projet2sdvBundle:stypeProduits', 't', 'with', 'p.typeProduit=t.id')
            ->addOrderBy('p.nom', 'ASC');
        $query = $qb->getQuery();
        $query->setFirstResult(($page-1)*$nbParPage)
			->setMaxResults($nbParPage);
        return new Paginator($query, true);
    }
}
