<?php

namespace projet2sdvBundle\Repository;

/**
 * stypeProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stypeProduitsRepository extends \Doctrine\ORM\EntityRepository
{
}
